# Estructuras repetitivas y Funciones

# Estructuras repetitivas

In [ ]:
#ciclo for
print("Ciclo for en un rango de datos: ")
for i in range(2,10):
    print(i)

print('Ciclo for en una coleccion de datos:')
x=[3,4,5,7,8,"Hola"]
for i in x:
    print("El elemento es= ",i)
for i in range(len(x)):
    print("El elemento de la posicion",i,'es:',x[i])

Ciclo for en un rango de datos: 
2
3
4
5
6
7
8
9
Ciclo for en una coleccion de datos:
El elemento es=  3
El elemento es=  4
El elemento es=  5
El elemento es=  7
El elemento es=  8
El elemento es=  Hola
El elemento de la posicion 0 es: 3
El elemento de la posicion 1 es: 4
El elemento de la posicion 2 es: 5
El elemento de la posicion 3 es: 7
El elemento de la posicion 4 es: 8
El elemento de la posicion 5 es: Hola


In [ ]:
print('Ciclo for en un diccionario:')
frutas = {'Fresa':'roja', 'Limon':'verde', 'Papaya':'naranja', 'Manzana':'amarilla', 'Guayaba':'rosa'}
for nombre, color in frutas.items():
    print (nombre, "es de color", color)
for llave in frutas:
    print(llave, 'es de color', frutas[llave])

Ciclo for en un diccionario:
Fresa es de color roja
Limon es de color verde
Papaya es de color naranja
Manzana es de color amarilla
Guayaba es de color rosa
Fresa es de color roja
Limon es de color verde
Papaya es de color naranja
Manzana es de color amarilla
Guayaba es de color rosa


In [ ]:
frutas

{'Fresa': 'roja',
 'Limon': 'verde',
 'Papaya': 'naranja',
 'Manzana': 'amarilla',
 'Guayaba': 'rosa'}

In [ ]:
frutas = {'Fresa':'roja', 'Limon':'verde', 'Papaya':'naranja', 'Manzana':'amarilla', 'Guayaba':'rosa'}
frutas

{'Fresa': 'roja',
 'Limon': 'verde',
 'Papaya': 'naranja',
 'Manzana': 'amarilla',
 'Guayaba': 'rosa'}

In [ ]:
len(frutas)

5

In [ ]:
frutas.get('Fresa')

'roja'

In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
v=['a','b','c','d']

for i in range(len(v)):
    print(i,"-->",v[i])


0 --> a
1 --> b
2 --> c
3 --> d


In [ ]:
for i in v:
    print(i)

a
b
c
d


In [ ]:
#ciclo while
cont=0
while cont<10:
    print(cont)
    cont+=2

0
2
4
6
8


In [ ]:
v=['a','b','c','d']

In [ ]:
for i in range(len(v)):
  print(i,v[i])

0 a
1 b
2 c
3 d


In [ ]:
for i in v:
  print(i)

a
b
c
d


## Ejercicio

1. Realice un programa que lea las notas de un estudiante, despues devolver el promedio, la mejor y la peor nota.

In [ ]:
# Escribe aquí tu código


# Funciones

Python es un lenguaje **indentado**, no usa corchetes para delimitar el alcance de las estructuras de programación sino que se fija en los **cambios de indentación**.

No se declara el tipo de los argumentos de las funciones. La semática de la implementación ha de estar preparada para funcionar con los tipos de datos que quieres.

In [ ]:
import numpy as np
def funcion_1(a,b):
    r = a**2
    return r+b

def greatest(a,b):
    if a>b:
        return a
    else:
        return b

In [ ]:
funcion_1 (10.4,2)

110.16000000000001

In [ ]:
funcion_1 (10.4, np.array([2,4]))

array([110.16, 112.16])

In [ ]:
funcion_1(np.array([1,5]),np.array([3,2]))

array([ 4, 27])

In [ ]:
m1 = np.array([[3,4],[1,1]])
m2 = np.array([[5,6],[0,0]])

funcion_1 (m1,m2)

array([[14, 22],
       [ 1,  1]])

In [ ]:
greatest(10,2)

10

Podemos definir valores por defecto para los argumentos de las funciones y llamarlas usando explícitamente el nombre de los argumentos. Además, las funciones pueden devolver varios valores.

In [ ]:
def f_power(x, p=2):
    return x**p

In [ ]:
f_power(x=3)

9

In [ ]:
f_power(p=4, x=3)

81

In [ ]:
def f_power(x, p=2):
    return x**p, x*p

In [ ]:
r = f_power(p=4, x=3)
print(r[0],r[1],"\n")

81 12 



In [ ]:
r1, r2 = f_power(p=4, x=3)
print(r1)
print(r2,"\n")

81
12 



In [ ]:
a,b = 10, np.array([10,4,-3])
print(a)
print(b)

10
[10  4 -3]


In [ ]:
def f_power(x, p=2):
    return x**p

def f_powers(x, p1=2, p2=3):
    return x**p1, x**p2

In [ ]:
f_power(4)

16

In [ ]:
f_power(4,3)

64

In [ ]:
f_powers(4, p1=3)

(64, 64)

In [ ]:
xp1, xp2 = f_powers(4, p2=4, p1=3)
print("power1",xp1, "power2", xp2)

power1 64 power2 256


# Paso por valor y referencia

Dependiendo del tipo de dato que enviemos a la **función**, podemos diferenciar dos comportamientos:

**Paso por valor**: Se crea una copia local de la variable dentro de la función.

**Paso por referencia**: Se maneja directamente la variable, los cambios realizados dentro de la función le afectarán también fuera.

Tradicionalmente:

**Los tipos simples se pasan por valor**: Enteros, flotantes, cadenas, lógicos...

**Los tipos compuestos se pasan por referencia**: Listas, diccionarios, conjuntos...


**Ejemplo de paso por valor**

Como ya sabemos los números se pasan por valor y crean una copia dentro de la función, por eso no les afecta externamente lo que hagamos con ellos:

In [ ]:
def doblar_valor(x):
    x = 2*x
    return x

In [ ]:
x=10
doblar_valor(x)
print(x,doblar_valor(x))

10 20


Para modificar los tipos simples podemos devolverlos modificados y reasignarlos:

In [ ]:
x = 10
x = doblar_valor(x)
print(x)

20


**Ejemplo de paso por referencia**

Sin embargo las listas u otras colecciones, al ser tipos compuestos se pasan por referencia, y si las modificamos dentro de la función estaremos modificándolas también fuera:

In [ ]:
def doblar_valores(y):
    for i,n in enumerate(y):
        y[i] = 2*y[i]

In [ ]:
y=[1,2,3]

In [ ]:
doblar_valores(y)

In [ ]:
print(y)

[2, 4, 6]
