# Estructuras repetitivas y Funciones

Los programas utilizados hasta este momento han examinado conceptos de programación, tales como entradas, salidas, asignaciones, expresiones y operaciones, sentencias secuenciales y de selección. Sin embargo, muchos problemas requieren de características de repetición, en las que algunos cálculos o secuencia de instrucciones se repiten una y otra vez, utilizando diferentes conjuntos de datos.


## Introducción a interación y bucle

Supongamos que se desea sumar una lista de números escritos desde teclado, por ejemplo, calificaciones de los alumnos de una clase.

El medio conocido hasta ahora es leer los números y añadir sus valores a una variable SUMA que contenga las sucesivas sumas parciales. El valor de SUMA se incrementa cada vez que se lea un nuevo número.

In [1]:
# Definir variables
SUMA = 0

# Leer e ingresar números
numero = int(input("Ingrese un número: "))
SUMA = SUMA + numero

numero = int(input("Ingrese otro número: "))
SUMA = SUMA + numero

numero = int(input("Ingrese un tercer número: "))
SUMA = SUMA + numero

numero = int(input("Ingrese un cuarto número: "))
SUMA = SUMA + numero

# Mostrar la suma de los números ingresados
print("La suma de los números ingresados es:", SUMA)


Ingrese un número: 6
Ingrese otro número: 3
Ingrese un tercer número: 2
Ingrese un cuarto número: 5
La suma de los números ingresados es: 16


El algoritmo incrementa el valor de SUMA cada vez que se lee una variable numero.

En este algoritmo se repiten muchas veces las acciones:

```python
numero = int(input("Ingrese un cuarto número: "))
SUMA = SUMA + numero

```

---

Las estructuras que repiten una secuencia de instrucciones un número determinado de veces se denominan bucles y se denomina iteración al hecho de repetir la ejecución de una secuencia de acciones.


# Estructuras repetitivas

In [ ]:
#ciclo for
print("Ciclo for en un rango de datos: ")
for i in range(2,10):
    print(i)

print('Ciclo for en una coleccion de datos:')
x=[3,4,5,7,8,"Hola"]
for i in x:
    print("El elemento es= ",i)
for i in range(len(x)):
    print("El elemento de la posicion",i,'es:',x[i])

Ciclo for en un rango de datos: 
2
3
4
5
6
7
8
9
Ciclo for en una coleccion de datos:
El elemento es=  3
El elemento es=  4
El elemento es=  5
El elemento es=  7
El elemento es=  8
El elemento es=  Hola
El elemento de la posicion 0 es: 3
El elemento de la posicion 1 es: 4
El elemento de la posicion 2 es: 5
El elemento de la posicion 3 es: 7
El elemento de la posicion 4 es: 8
El elemento de la posicion 5 es: Hola


In [ ]:
print('Ciclo for en un diccionario:')
frutas = {'Fresa':'roja', 'Limon':'verde', 'Papaya':'naranja', 'Manzana':'amarilla', 'Guayaba':'rosa'}
for nombre, color in frutas.items():
    print (nombre, "es de color", color)
for llave in frutas:
    print(llave, 'es de color', frutas[llave])

Ciclo for en un diccionario:
Fresa es de color roja
Limon es de color verde
Papaya es de color naranja
Manzana es de color amarilla
Guayaba es de color rosa
Fresa es de color roja
Limon es de color verde
Papaya es de color naranja
Manzana es de color amarilla
Guayaba es de color rosa


In [ ]:
frutas

{'Fresa': 'roja',
 'Limon': 'verde',
 'Papaya': 'naranja',
 'Manzana': 'amarilla',
 'Guayaba': 'rosa'}

In [ ]:
frutas = {'Fresa':'roja', 'Limon':'verde', 'Papaya':'naranja', 'Manzana':'amarilla', 'Guayaba':'rosa'}
frutas

{'Fresa': 'roja',
 'Limon': 'verde',
 'Papaya': 'naranja',
 'Manzana': 'amarilla',
 'Guayaba': 'rosa'}

In [ ]:
len(frutas)

5

In [ ]:
frutas.get('Fresa')

'roja'

In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
v=['a','b','c','d']

for i in range(len(v)):
    print(i,"-->",v[i])


0 --> a
1 --> b
2 --> c
3 --> d


In [ ]:
for i in v:
    print(i)

a
b
c
d


In [ ]:
#ciclo while
cont=0
while cont<10:
    print(cont)
    cont+=2

0
2
4
6
8


In [ ]:
v=['a','b','c','d']

In [ ]:
for i in range(len(v)):
  print(i,v[i])

0 a
1 b
2 c
3 d


In [ ]:
for i in v:
  print(i)

a
b
c
d


<a name="1"></a>
## Ejemplo 1

Realiza un algoritmo que cuente las vocales de un `string`

In [ ]:
frase = "Anita lava la tina"
k = 0

for letra in frase.lower():
    if letra in ("a","e","i","o","u"):
        k += 1

print(f"Hay {k} vocales")

Hay 8 vocales


<a name="2"></a>
## Ejemplo 2

Realiza un programa que haga un triangulo de caracteres

In [ ]:
# Pista. En Python es posible multiplicar strings:

print('a'*3)
print("hola "*5)

aaa
hola hola hola hola hola 


In [ ]:
n = 10
for k in range(1,n+1):
    print("*"*k)

*
**
***
****
*****
******
*******
********
*********
**********


<a name="3"></a>
## Ejemplo 3

Realiza un programa que genere una tabla de multiplicación

In [ ]:
n = 2
for k in range(1,11):
    print(f"{n} x {k} = {n*k}")

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20


Tambien lo podemos hacer personalizable

In [ ]:
b= int(input("Ingresa el número del que quieres su tabla: "))
for i in range(1,10+1):
  result= int(b*i)
  print(b,"x", i, "=", str(result))

Ingresa el número del que quieres su tabla: 5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


<a name="4"></a>
## Ejemplo 4

Realizar un programa para calcular el factorial de un número n

In [ ]:
n = int(input("Ingrese un número entero: "))
factorial = 1

for i in range(1, n+1, 1):
    factorial = factorial * i
print("El factorial de n con parámetros 1, n+1, 1 es: ", factorial)

Ingrese un número entero: 6
El factorial de n con parámetros 1, n+1, 1 es:  720


<a name="5"></a>
## Ejemplo 5

Realiza un programa para generar secuencias con ciclo anidados

In [ ]:
n = int(input("Ingrese un número entero: "))

for i in range(1, n+1):
    for j in range (1, i+1):
        print(i, end="")
    print("")
print("")

for i in range(1, n+1):
    for j in range (1, i+1):
        print(j, end="")
    print("")
print("")

Ingrese un número entero: 6
1
22
333
4444
55555
666666

1
12
123
1234
12345
123456



<a name="6"></a>
## Ejemplo 6

Realiza un programa para generar secuencias con ciclo anidados de forma inversa

In [ ]:
n = int(input("Ingrese un número entero: "))

for i in range(n, 0, -1):
    for j in range (1, i+1):
        print(i, end="")
    print("")
print("")

for i in range(n, 0, -1):
    for j in range (i, 0, -1):
        print(j, end="")
    print("")
print("")

Ingrese un número entero: 8
88888888
7777777
666666
55555
4444
333
22
1

87654321
7654321
654321
54321
4321
321
21
1



## Ejercicio

1. Realice un programa que lea las notas de un estudiante, despues devolver el promedio, la mejor y la peor nota.

In [ ]:
# Escribe aquí tu código


# Funciones

Python es un lenguaje **indentado**, no usa corchetes para delimitar el alcance de las estructuras de programación sino que se fija en los **cambios de indentación**.

No se declara el tipo de los argumentos de las funciones. La semática de la implementación ha de estar preparada para funcionar con los tipos de datos que quieres.

In [ ]:
import numpy as np
def funcion_1(a,b):
    r = a**2
    return r+b

def greatest(a,b):
    if a>b:
        return a
    else:
        return b

In [ ]:
funcion_1 (10.4,2)

110.16000000000001

In [ ]:
funcion_1 (10.4, np.array([2,4]))

array([110.16, 112.16])

In [ ]:
funcion_1(np.array([1,5]),np.array([3,2]))

array([ 4, 27])

In [ ]:
m1 = np.array([[3,4],[1,1]])
m2 = np.array([[5,6],[0,0]])

funcion_1 (m1,m2)

array([[14, 22],
       [ 1,  1]])

In [ ]:
greatest(10,2)

10

Podemos definir valores por defecto para los argumentos de las funciones y llamarlas usando explícitamente el nombre de los argumentos. Además, las funciones pueden devolver varios valores.

In [ ]:
def f_power(x, p=2):
    return x**p

In [ ]:
f_power(x=3)

9

In [ ]:
f_power(p=4, x=3)

81

In [ ]:
def f_power(x, p=2):
    return x**p, x*p

In [ ]:
r = f_power(p=4, x=3)
print(r[0],r[1],"\n")

81 12 



In [ ]:
r1, r2 = f_power(p=4, x=3)
print(r1)
print(r2,"\n")

81
12 



In [ ]:
a,b = 10, np.array([10,4,-3])
print(a)
print(b)

10
[10  4 -3]


In [ ]:
def f_power(x, p=2):
    return x**p

def f_powers(x, p1=2, p2=3):
    return x**p1, x**p2

In [ ]:
f_power(4)

16

In [ ]:
f_power(4,3)

64

In [ ]:
f_powers(4, p1=3)

(64, 64)

In [ ]:
xp1, xp2 = f_powers(4, p2=4, p1=3)
print("power1",xp1, "power2", xp2)

power1 64 power2 256


# Paso por valor y referencia

Dependiendo del tipo de dato que enviemos a la **función**, podemos diferenciar dos comportamientos:

**Paso por valor**: Se crea una copia local de la variable dentro de la función.

**Paso por referencia**: Se maneja directamente la variable, los cambios realizados dentro de la función le afectarán también fuera.

Tradicionalmente:

**Los tipos simples se pasan por valor**: Enteros, flotantes, cadenas, lógicos...

**Los tipos compuestos se pasan por referencia**: Listas, diccionarios, conjuntos...


**Ejemplo de paso por valor**

Como ya sabemos los números se pasan por valor y crean una copia dentro de la función, por eso no les afecta externamente lo que hagamos con ellos:

In [ ]:
def doblar_valor(x):
    x = 2*x
    return x

In [ ]:
x=10
doblar_valor(x)
print(x,doblar_valor(x))

10 20


Para modificar los tipos simples podemos devolverlos modificados y reasignarlos:

In [ ]:
x = 10
x = doblar_valor(x)
print(x)

20


**Ejemplo de paso por referencia**

Sin embargo las listas u otras colecciones, al ser tipos compuestos se pasan por referencia, y si las modificamos dentro de la función estaremos modificándolas también fuera:

In [ ]:
def doblar_valores(y):
    for i,n in enumerate(y):
        y[i] = 2*y[i]

In [ ]:
y=[1,2,3]

In [ ]:
doblar_valores(y)

In [ ]:
print(y)

[2, 4, 6]
